
name: ESLint Workflow
on:
  push:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - master
      - edge

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'

  pull_request:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - master
      - edge

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installs all global packages
        run: yarn global add eslint typescript

      - name: Installs local packages
        run: yarn

      - name: Lints the repository and checks for linting errors
        run: eslint src --ext .ts

      - name: Compiles the project to check for any build errors
        run: tsc --noEmit
